FROM golang:1.22-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /usr/local/taskhub/main

COPY /src .
RUN go mod download

# RUN go build -o main-app main.go

EXPOSE 8080


# CMD [ "./main-app" ]
# CMD ["air", "-c", ".air.toml"]
ENTRYPOINT [ "air" ]